### ISSUE TITLE
Server error when starting resource

### ISSUE THREAD

**Issue by ansljeremy** [TheKingFyre/QB-Detector#1]
[    c-scripting-core] Creating script environments for qb-detector
[  script:qb-detector] Error loading script server/sv_detector.lua in resource qb-detector: @qb-detector/server/sv_detector.lua:1: attempt to index a nil value (field 'Framework')
[  script:qb-detector] stack traceback:
[  script:qb-detector] 	@qb-detector/server/sv_detector.lua:1: in main chunk
[    c-scripting-core] Failed to load script server/sv_detector.lua.
[ citizen-server-impl] Started resource qb-detector

**Comment by TheKingFyre** [comment]
pushed an update to fix the issue
