### ISSUE TITLE
error given and not functioning 

### ISSUE THREAD

**Issue by CodeOperator-dev** [TheKingFyre/QB-Detector#2]
followed the readme 
turned off the tnotify as i don't use them
and started it gives me this error
![image](https://user-images.githubusercontent.com/80795865/147402323-3909e591-6b5c-4fb1-9b9e-ef8c81814c63.png)
even tho it says it started it doesn't do anything in game [yes just want to add that if that error is known]

**Comment by TheKingFyre** [comment]
This has nothing to do with T-notify, Read the actual error . its Talking About FIeld Framework, Meaning its not connecting to your servers frame work correctly. What version of QBCore are you running? Cause the way this older script was written at the time was using QBCores old way of importing the framework info. If you are using the newest commits from QBCore its a small simple fix.

**Comment by shane0011** [comment]
what do i have to fix if i am using the newest qbcore?

**Comment by iboss21** [comment]
i have rewrite this script fully, thanks for idea thow

**Comment by ACEs-Developer** [comment]
> i have rewrite this script fully, thanks for idea thow

can u send it over

**Comment by ACEs-Developer** [comment]
> This has nothing to do with T-notify, Read the actual error . its Talking About FIeld Framework, Meaning its not connecting to your servers frame work correctly. What version of QBCore are you running? Cause the way this older script was written at the time was using QBCores old way of importing the framework info. If you are using the newest commits from QBCore its a small simple fix.

how do u fix
